### ISSUE TITLE
app crashes after selecting a file on android

### ISSUE THREAD

**Issue by cxFreeze** [epicshaggy/capacitor-file-picker#5]
`java.lang.IllegalArgumentException: method com.epicshaggy.filepicker.FilePicker.filePickerResult argument 2 has type android.app.Instrumentation$ActivityResult, got androidx.activity.result.ActivityResult
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.Plugin.triggerActivityCallback(Plugin.java:154)
        at com.getcapacitor.Plugin.lambda$initializeActivityLaunchers$0$Plugin(Plugin.java:116)
        at com.getcapacitor.-$$Lambda$Plugin$9tit0PZrRMA5UA4Z_xqI4yDk4JY.onActivityResult(Unknown Source:6)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
        at android.app.Activity.dispatchActivityPostStarted(Activity.java:1279)
        at android.app.Activity.performStart(Activity.java:7967)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3335)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

using Capacitor 3, android 10 ,target SDK 30

plugin v 1.0.10

do you know what causes this ? thank you

**Comment by derbenoo** [comment]
Experiencing the same problem:

`method com.epicshaggy.filepicker.FilePicker.filePickerResult argument 2 has type android.app.Instrumentation$ActivityResult, got androidx.activity.result.ActivityResult`
